#Здесь будут инструменты для работы с ботом
import json

#сохраняем print(message)

#найти ошибки и поставить ковычки ['<telebot.types.MessageEntity object at 0x0000021856188DC0>']
message = {'content_type': 'text', 'id': 1, 'message_id': 1, 'from_user': {'id': 84779542, 'is_bot': False, 'first_name': 'Евгений', 'username': 'FomichevEvgeniy', 'last_name': 'Фомичев', 'language_code': None, 'can_join_groups': None, 'can_read_all_group_messages': None, 'supports_inline_queries': None}, 'date': 1625725112, 'chat': {'id': 84779542, 'type': 'private', 'title': None, 'username': 'FomichevEvgeniy', 'first_name': 'Евгений', 'last_name': 'Фомичев', 'photo': None, 'bio': None, 'description': None, 'invite_link': None, 'pinned_message': None, 'permissions': None, 'slow_mode_delay': None, 'sticker_set_name': None, 'can_set_sticker_set': None, 'linked_chat_id': None, 'location': None}, 'forward_from': None, 'forward_from_chat': None, 'forward_from_message_id': None, 'forward_signature': None, 'forward_sender_name': None, 'forward_date': None, 'reply_to_message': None, 'edit_date': None, 'media_group_id': None, 'author_signature': None, 'text': '/start', 'entities': ['<telebot.types.MessageEntity object at 0x0000021856188DC0>'], 'caption_entities': None, 'audio': None, 'document': None, 'photo': None, 'sticker': None, 'video': None, 'video_note': None, 'voice': None, 'caption': None, 'contact': None, 'location': None, 'venue': None, 'animation': None, 'dice': None, 'new_chat_member': None, 'new_chat_members': None, 'left_chat_member': None, 'new_chat_title': None, 'new_chat_photo': None, 'delete_chat_photo': None, 'group_chat_created': None, 'supergroup_chat_created': None, 'channel_chat_created': None, 'migrate_to_chat_id': None, 'migrate_from_chat_id': None, 'pinned_message': None, 'invoice': None, 'successful_payment': None, 'connected_website': None, 'reply_markup': None, 'json': {'message_id': 1, 'from': {'id': 84779542, 'is_bot': False, 'first_name': 'Евгений', 'last_name': 'Фомичев', 'username': 'FomichevEvgeniy'}, 'chat': {'id': 84779542, 'first_name': 'Евгений', 'last_name': 'Фомичев', 'username': 'FomichevEvgeniy', 'type': 'private'}, 'date': 1625725112, 'text': '/start', 'entities': [{'offset': 0, 'length': 6, 'type': 'bot_command'}]}}

#Лучше делать так, чтобы понимать что находится в сообщении
with open('message_json.json', mode='w', encoding='utf-8') as json_file:
    json.dump(message, json_file, indent=4, ensure_ascii=False) #Закидываем в json файл красиво и без кодировки в ASCI